# -*- coding: utf-8 -*-
"""resize gambar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcVUI4ILlDuAKWDLSeZY2qcwQXDSIj6w
"""

from google.colab import files
from PIL import Image

def resize_image(image_path, output_path, width, height):
    # Load image
    img = Image.open(image_path)

    # Resize image
    resized_img = img.resize((width, height))

    # Save resized image
    resized_img.save(output_path)
    print(f"Image resized and saved to {output_path}")

# Upload image file
uploaded = files.upload()

# Specify input and output paths
input_path = next(iter(uploaded))
output_path = "hasilkompres.jpg"  # Change the output path if needed

# Specify target width and height
target_width = 300
target_height = 200

# Resize image
resize_image(input_path, output_path, target_width, target_height)